### ISSUE TITLE
update readme to suggest `$XDG_CONFIG_HOME` as directory for settings.toml

### ISSUE THREAD

**Issue by skewballfox** [maxjoehnk/sidenotes#51]
I was going to suggest making the project xdg compliant, but looking through the code it looks like it already is, it seems to be checking the config directory by default. You should probably update the readme to tell users to create the directory in `$XDG_CONFIG_HOME`.

**Comment by maxjoehnk** [comment]
There was a typo as well which I've fixed as well. Thanks for the hint.
